server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
